options:





#-----------------------------#
#   If you like the plugin    #
#   Make sure to rate it ❤   #
#-----------------------------#





    prefix: &8&l[&fItem Display&8&l]&r  # General prefix
	
    keywords: "[item]" or "[i]"
	
    msgchat: &f&l%player% &7&l>>&r  # The message that shows before the player's listed item in the chat. (Player's name by default)
	
    msgcd: &fYou can use that again in&7  # Message when the player has to wait in order to list their item again
	
    cooldown: 15 second  # The cooldown the player is able to show items in the chat
	
    permission: idp.item  # Permission node





# Do not change anything below or the plugin won't fuction properly !
on chat:
    if message contains {@keywords}:
        cancel event
        wait 2 tick
    else:
        stop
    if player doesn't have permission "{@permission}":
        message "{@prefix} You do not have permission to do that."
        stop
        wait 2 tick
    if player's held item is air:
        message "{@prefix} You need to have an item on your hand."
        stop
    if difference between now and {chatitemcd::%player%} is less than {@cooldown}:
        send "{@prefix} {@msgcd} %difference between {@cooldown} and difference between now and {chatitemcd::%player%}%"
        stop
        wait 2 tick
    else:
        wait 1 tick
        set {chatitemcd::%player%} to now
        set {_name} to name of player's item or block or tool
        if {_name} isn't set:
            set {_name} to type of player's item or block or tool
        set {_Lore} to "%lore of player's item or block or tool%"
        replace all ", " and " and " with "\n" in {_Lore}
        if {_Lore} is "<none>":
            set {_Lore} to ""
        set {_amount} to "&6x%item amount of player's item or block or tool%"
        if {_amount} is "&6x1":
            set {_amount} to ""
        set {_enchants::*} to player's item or block or tool's enchantments
        set {_enchant} to ""
        set {_enchant} to "%{_enchant}%\n&7%{_enchants::*}%"
        set {_enchant} to "%{_enchant}%\n"
        replace all ", " and " and " with "\n" in {_Enchant}
        wait 1 tick
        execute console command "/tellraw @a [{""text"":""{@msgchat} ""},{""text"":""%{_name}% %{_amount}%"",""hoverEvent"":{""action"":""show_text"",""value"":[{""text"":""%{_name}% %{_amount}%""},{""text"":""%{_enchant}%%{_Lore}%""}]}}]"
on script load:
    wait 1 second
    send "&aEnabling &7Item Display Pro ~ 1.0.1" to the console
    wait 5 seconds
    send "&r                                     " to the console
    send "&7      Item Display Pro ~&r 1.0.1       " to the console
    send "&r                                     " to the console
    send "&r          &7Developed by Nik&r           " to the console
    send "&r                                     " to the console